frr version 8.5.1
hostname r7
interface eth1
 ip address 10.3.3.2/24
interface eth2
 ip address 10.3.4.1/24
router bgp 65104
 bgp router-id 7.7.7.7
 neighbor 10.3.3.1 remote-as 65103
 neighbor 10.3.4.2 remote-as 65105
