frr version 8.5.1
hostname r4
interface eth1
 ip address 10.2.1.2/24
interface eth2
 ip address 10.3.1.1/24
router bgp 65101
 bgp router-id 4.4.4.4
 neighbor 10.2.1.1 remote-as 65003
 neighbor 10.3.1.2 remote-as 65102
