frr version 8.5.1
hostname r1
interface eth1
 ip address 10.1.1.1/24
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 10.1.1.2 remote-as 65002
 address-family ipv4 unicast
  network 192.168.10.0/24
 exit-address-family
